export const ROOTS: string[];
export function dirName(name: string): string;
export function pathOf(name: string): string;
export function nameAt(root: string, dir: string): string | undefined;
export const LOCATIONS: Record<string, "packages" | "plugins" | "apps">;
export const ADAPTERS: string[];
export const ALLOWED: Record<string, string[] | "*">;
export const NAMES: string[];
export const TEST_SUPPORT: string;
export function isAllowed(from: string, to: string, options?: { test?: boolean }): boolean;
export function allowedOf(from: string): string[];
